### ISSUE TITLE
Possibility to flash BLE400 board using stlink protocol

### ISSUE THREAD

**Issue by altrunner** [platformio/platform-nordicnrf51#13]
I upload firmware to my BLE400 board using stlink programmer,
to make it possible I had to manually register stlink as debugger tool in waveshare_ble400.json. 
Could you please update the platform definition so I don't have to do it manually?

**Comment by jeanmatthieud** [comment]
Same request for nrf51_dk board

**Comment by ivankravets** [comment]
Implemented in https://github.com/platformio/platform-nordicnrf51/commit/d95b50fba0305b5e7aae234c052e00369668947c

Please use in your `platformio.ini`
```
[env:...]
...
upload_protocol = stlink
debug_tool = stlink
```
