### ISSUE TITLE
Compiled code with mbed for NRF51 doesn't run

### ISSUE THREAD

**Issue by Gecko05** [platformio/platform-nordicnrf51#15]
I'm relatively new to PlatformIO and I've been trying to run a simple example program for the NRF51. Had no trouble using mbed online with several examples but none of the examples in the PlatformIO seem to work on NRF51, can't even run a single blink led program. 
The only suspicious thing I get is "arm-none-eabi-g++: error: CreateProcess: No such file or directory" in my "main.cpp" file when saving the project.
Everything seems up to date and the code for other platforms like Nucleo and KLK46Z works fine.

**Comment by valeros** [comment]
Hi, @Gecko05! What is your OS? Could you please provide full build and upload logs?

**Comment by Gecko05** [comment]
I'm using Windows 10, here are my build logs [logs.txt](https://github.com/platformio/platform-nordicnrf51/files/1278319/logs.txt), unfortunately I lack the upload logs, I'm using a J-link to upload the hex generated from Platformio, I'm doing the same for the .hex generated from the mbed compiler. Hope it's enough, thanks.

**Comment by valeros** [comment]
PlatformIO generates two `.hex` files:  `userfirmware.hex` and `firmware.hex`. Which one do you upload?

**Comment by Gecko05** [comment]
firmware.hex

**Comment by Gecko05** [comment]
Is there a way to upload the code via Platformio using the J-link?

**Comment by zerog2k** [comment]
@Gecko05 nrfjprog

**Comment by Gecko05** [comment]
Seems like my hardware is only able to run with a softdevice 130
