### ISSUE TITLE
Support STLink as upload protocol for mbed

### ISSUE THREAD

**Issue by jeanmatthieud** [platformio/platform-nordicnrf51#16]
As it is for ststm32 platform.
Currently, only JLINK OB is supported.

**Comment by ivankravets** [comment]
Implemented in https://github.com/platformio/platform-nordicnrf51/commit/d95b50fba0305b5e7aae234c052e00369668947c

Please use in your `platformio.ini`
```
[env:...]
...
upload_protocol = stlink
debug_tool = stlink
```
