### ISSUE TITLE
Waveshare BLE400 missing mbed

### ISSUE THREAD

**Issue by webfrank** [platformio/platform-nordicnrf51#22]
PLATFORM: Nordic nRF51 > Waveshare BLE400
SYSTEM: NRF51822 32MHz 32KB RAM (256KB Flash)
DEBUG: CURRENT(blackmagic) EXTERNAL(blackmagic, jlink, stlink)
Error: This board doesn't support mbed framework!

**Comment by ivankravets** [comment]
This board does not support mbed https://www.waveshare.com/wiki/BLE400

Nevertheless, you can try to use "Nordic nRF51-DK" `nrf51_dk` as a board.
