### ISSUE TITLE
zephir-ble-eddystone example

### ISSUE THREAD

**Issue by gerisse** [platformio/platform-nordicnrf51#35]
hi,
trying to build the zephir-ble-eddystone example, with bbc microbit board, this issue apparead :

~/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld: region `SRAM' overflowed by 572 bytes   (103 %)

Just  a issue with zephyr , or with duo zephyr-pio ?
thanks

**Comment by valeros** [comment]
Hi @gerisse ! The issue means that your project doesn't fit into available memory. You can either optimize your SRAM usage or switch to an MCU with larger SRAM size.

**Comment by gerisse** [comment]
yes, of course, but i 'm surprised that an standard example given by official source is not running ...

**Comment by valeros** [comment]
Could you please try to compile the same example using the native `west` tool?
