### ISSUE TITLE
Error "BLE_API.h: No such file or directory" upon building BLE central test example

### ISSUE THREAD

**Issue by vorlovsky** [platformio/platform-nordicnrf51#37]
I've imported [BLE_CentralTest](https://github.com/redbear/nRF5x/blob/master/nRF51822/arduino/arduino-1.6.x/hardware/RBL/RBL_nRF51822/libraries/BLE_Examples/examples/BLE_CentralTest/BLE_CentralTest.ino) example from Arduino and tried to build it for nRF51822 with PlatformIO, but got stuck on "BLE_API.h: No such file or directory" error. 
I've tried to select Platformio or Arduino as a library manager upon project import, but no luck. 
Also. there is no such error if to build the same sketch using Arduino IDE. 

How can this dependencies be fixed in PlatformIO?

Build task output is the following:

> Processing nrf51 (platform: nordicnrf51; board: seeedTinyBLE; framework: arduino)  
> ---------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option  
> CONFIGURATION: https://docs.platformio.org/page/boards/nordicnrf51/seeedTinyBLE.html  
> PLATFORM: Nordic nRF51 (6.0.1) > Seeed Tiny BLE  
> HARDWARE: NRF51822 16MHz, 16KB RAM, 256KB Flash  
> DEBUG: Current (cmsis-dap) On-board (cmsis-dap) External (blackmagic, jlink, stlink)  
> PACKAGES:  
>  - framework-arduinonordicnrf5 1.600.190830 (6.0)  
>  - tool-sreccat 1.164.0 (1.64)  
>  - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)  
> Converting arduino-central-test.ino
> LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 2 compatible libraries
> Scanning dependencies...
> No dependencies
> Building in release mode
> Compiling .pio\build\nrf51\src\arduino-central-test.ino.cpp.o
> Compiling .pio\build\nrf51\FrameworkArduinoVariant\variant.cpp.o
> Compiling .pio\build\nrf51\FrameworkArduino\IPAddress.cpp.o
> Compiling .pio\build\nrf51\FrameworkArduino\Print.cpp.o
> E:/nRF51/projects/arduino-central-test/src/arduino-central-test.ino:21:10: fatal error: BLE_API.h: No such file or directory
> 
> *****************************************************************
> * Looking for Archiving .pio\build\nrf51\libFrameworkArduinoVariant.a
> BLE_API.h dependency? Check our library registry!
> *
> * CLI  > platformio lib search "header:BLE_API.h"
> * Web  > https://platformio.org/lib/search?query=header:BLE_API.h
> *
> *****************************************************************
> 
>  #include <BLE_API.h>
>           ^~~~~~~~~~~
> compilation terminated.
> *** [.pio\build\nrf51\src\arduino-central-test.ino.cpp.o] Error 1
> ================================================== [FAILED] Took 2.25 seconds ==================================================
> The terminal process "C:\Users\LJ\.platformio\penv\Scripts\pio.exe 'run'" terminated with exit code: 1.

**Comment by valeros** [comment]
Hi @vorlovsky ! The example you mentioned is supposed to work with Arduino core from RedBear. This platform only supports the Arduino nRF5 core https://github.com/sandeepmistry/arduino-nRF5

**Comment by vorlovsky** [comment]
@valeros Do you mean I need to use Arduino nRF5 core instead of the one provided by default for the `nordicnrf51` platform? Is it possible to specify it somehow in `platformio.ini`? I see it is possible for STM32 (through `board_build.core` option), but what about nRF5?

**Comment by valeros** [comment]
Unfortunately, there is no support for the Arduino core from RedBearLab at the moment.

**Comment by vorlovsky** [comment]
Thanks.
