### ISSUE TITLE
Support for Waveshare NRF51822 Eval Kit

### ISSUE THREAD

**Issue by ivankravets** [platformio/platform-nordicnrf51#4]
# Moved from https://github.com/platformio/platformio/issues/655

/cc @digitalstreamio @sabas1080
------

Any thoughts on what it would take to support this nRF51822 based board?

http://www.waveshare.com/product/modules/wireless/bluetooth/nrf51822-eval-kit.htm
http://www.waveshare.com/wiki/NRF51822_Eval_Kit

**Comment by sabas1080** [comment]
Hi
Here is an example with Arduino Core
https://github.com/sandeepmistry/arduino-nRF5

**Comment by ivankravets** [comment]
Added in the latest release.
