### ISSUE TITLE
Support Redbearlab BLE Nano with Arduino

### ISSUE THREAD

**Issue by danlsk** [platformio/platform-nordicnrf51#5]
The current platformIO uses the mbed framework like mbed web IDE. The Arduino version is not supported and may not able to use those Arduino libraries. Also, please make sure it can support these Arduino libraries for nrf5x:
[Arduino nrf5](https://github.com/sandeepmistry/arduino-nRF5)
[BLEPeripheral](https://github.com/sandeepmistry/arduino-BLEPeripheral)

**Comment by ivankravets** [comment]
Added in the latest release
